name: Python CI
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10.', '3.11', 'pypy3.8']
    steps:
    - uses: microsoft/action-python/.github/workflows/validation.yml@0.7.0
      with:
        workdir: '.'
        python-version: ${{ matrix.python-version }}

  

  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.7.0
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
